### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ljcyt** [shaxiu/njtech_grabber#6]
大佬，您好，我们学校的可能和你们学校的网站不一样，我运行脚本他报错python utils.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/ll/123/utils.py", line 16, in <module>
    lgn.login(userName, passWord)  # 登陆
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/ll/123/login.py", line 28, in login
    tokens = soup.find(id='csrftoken').get("value")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'我通过chatgpt查找得知soup.find(id ='csrftoken')函数返回了None，于是我尝试把第33行代码的1改为了none。但是还是报错，所以我想请教一下这种情况该怎么修改代码啊，😁

**Comment by shaxiu** [comment]
这个脚本暂时只适用于正方的系统，所以自动登录的逻辑可能你那边得改下
